receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 80
    spike_limit_mib: 20
  batch:
    timeout: 1s
    send_batch_size: 64
exporters:
  otlphttp:
    endpoint: http://jaeger:4318
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp]
